import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat_Alternates, Montserrat } from "next/font/google";
import "./globals.scss";

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlternates.variable} ${montserrat.variable} root-body`}
      >
        {children}
      </body>
    </html>
  );
}
